### PR TITLE
Scaling documentation and updates for scaling algorithm 

### PR DESCRIPTION
**Pull request by LSchmidtEn**
Closes Issue # (if applicable).

## Changes proposed in this Pull Request
- Scaling Documentation added 
- Printing of numerical improvements added to scaling algorithm 

## Checklist

- [ ] Code changes have been tested locally.
- [ ] Code changes are sufficiently documented, i.e. new functions contain docstrings and further explanations may be given in `docs`.
- [ ] A note for the release notes `docs/files/release_notes.rst` is included.
- [ ] Breaking changes are documented in the `docs` and are communicated to the user (if applicable).
- [ ] Newly introduced dependencies are added to `pyproject.toml` (if applicable).
- [ ] Tests for new features were added (if applicable).

### CODE REVIEW

**Comment by LSchmidtEn** [comment]
@jacob-mannhardt please review

**Review by jacob-mannhardt — CHANGES_REQUESTED** [review]
the benchmarking workflow is still in there, but I think that is ok. The `save_benchmarking_results` option in the default config should be described in [files/configurations.rst](https://github.com/ZEN-universe/ZEN-garden/blob/main/docs/files/configurations.rst)

**Comment by jacob-mannhardt** [comment]
why do you only have the comparisons for PI_small? (the box plots with the 4 options) I would suggest doing that for all models

**Comment by jacob-mannhardt** [comment]
I really like the way you discussed the scaling tho! well done!

**Review by jacob-mannhardt — APPROVED** [review]

**Pull request merged**
