### PR TITLE
Updated API-docs

### PR DESCRIPTION
**Pull request by LSchmidtEn**
Closes Issue # (if applicable).

## Changes proposed in this Pull Request
-Updated API docs
-Updated mathematical formulation of constraints in function headers
-Updated class/function headers

## Checklist

- [ ] Code changes have been tested locally.
- [ ] Code changes are sufficiently documented, i.e. new functions contain docstrings and further explanations may be given in `docs`.
- [ ] A note for the release notes `docs/files/release_notes.rst` is included.
- [ ] Breaking changes are documented in the `docs` and are communicated to the user (if applicable).
- [ ] Newly introduced dependencies are added to `pyproject.toml` (if applicable).
- [ ] Tests for new features were added (if applicable).

### CODE REVIEW

**Comment by LSchmidtEn** [comment]
@jacob-mannhardt please check and confirm

**Comment by jacob-mannhardt** [comment]
Looking good!! Thanks! 
Some minor points that I have spotted

Technology:
`constraint_technology_construction_time()`
- you have missed the year shift between the investment and construction´

`constraint_technology_diffusion_limit()`
- there are two constraints in this block. One for all locations together, and one with spillover effects (see mathematical formulation)
- you have only formulated the constraint for transport technologies

`constraint_technology_capacity_limit()`
- please add an arrow or a : between "if existing capacities < capacity limit" and the maths (same for the constraints in transport tech)

`constraint_technology_lifetime`
- \delta s^{ex} must be lower case

`constraint_technology_min_capacity_addition`
- weird formatting of g_{i,p,y}

Carrier:
`constraint_availability_import_export_yearly`
- weird formatting of the maths

`constraint_cost_limit_shed_demand`
- line break missing in maths

Conversion Technology:
`constraint_opex_emissions_technology_conversion`
- index of O_{h,p,t) not in subscript

Storage technology
`constraint_couple_storage_level`
- you've copied the wrong equation, the correct one is this https://zen-garden.readthedocs.io/en/latest/files/zen_garden_in_detail/mathematical_formulation.html#equation-storage-level

`constraint_capacity_energy_to_power_ratio`
- this makes more sense than what is in the mathematical formulation
- but normally we wouldn't write S^{power}, but just S

Energy System:
`constraint_carbon_emissions_annual_overshoot`
- there is something missing in the constraint (only a symbol right now)

`constraint_carbon_emissions_budget`
- maths is not shown

`constraint_carbon_emissions_budget_overshoot`
- add condition when this is 0 to the constraint, same with `constraint_carbon_emissions_annual_overshoot`

`objective_total_carbon_emissions`
- we changed it to actually just minimize the cumulative emissions in the last time step. Could you please also change that in the mathematical formulation

**Comment by LSchmidtEn** [comment]
"Where to get help" also added now and updated mathematical formulation of the emissions objective functions.

**Comment by LSchmidtEn** [comment]
@jacob-mannhardt please check and confirm

**Pull request merged**
